### ISSUE TITLE
TS - decrease number for partialRootPaths

### ISSUE THREAD

**Issue by soophie** [tritum/form_element_linked_checkbox#13]
In `FormSetup.yaml` the partialRootsPaths are defined with a very huge number (`1505042806`). Is there a specific reason for this?

Could you decrease this number? Otherwise my custom configuration needs a higher number only for this extension.

**Comment by tritum** [comment]
This number is a unix timestamp (see https://www.unixtimestamp.com/index.php). We recommend using it. This way, we can be very sure to have no conflicts with other configuration files people have integrated so far. The probability users included their files within this second is very low. Using numbers like 10, 20 or something like that is not fail safe.

Does this work for you? Do you agree? Can we close this issue?

**Comment by soophie** [comment]
okay, I understand your point. In my case with custom Form Templates this is not really obvious, but a higher number in my custom config will work.

**Comment by tritum** [comment]
Thank you for your feedback. I am glad you've found a solution.

**Comment by iamwebrocker** [comment]
Sorry for reopen this for clarification. 
Does using a unixtimestamp in your case mean that whenever you release a new version, this timestamped key will increase?
While in principle I agree with the reasoning that this ensures that your def will not clash with other user defined keys, I see a potential gotcha: especially the case with defining the path to the templates or partials. since they are resolved from the highest key to the lowest, your timestamp key has a very high potential to always come first - even before a site_package that may need to overwrite the FORM template/partials paths. Now, if an site_package author stumbles across this and adjusts her keys to be higher than your timestamp - and with the next release your timestamp increases (?) and is again higher than the site_package, this creates an evergoing race, constantly changing the keys. Which to me sounds like trouble on the long run, especially for authors of site_packages… ?
