### ISSUE TITLE
conflict with EXT:recaptcha

### ISSUE THREAD

**Issue by t3webman** [tritum/form_element_linked_checkbox#3]
Thanks for this integration, howevere I have one bug:
I use v8.7.10 and also EXT:recaptcha, once this ext. was installed the recaptcha field losses its 'interface appearance' in the backend editor ... it still works (at least the fields that I integrated prior) ...

**Comment by tritum** [comment]
Hey @t3webman. Haven't tested the problem yet. But could you please update to the latest TYPO3 core bugfix version ( 8.7.18)? I highly recommend this since we had some severe security issues in the core (even related to the form framework). After you've updated the core can you check the problem again? Thx mate!

**Comment by tritum** [comment]
No reply since a long time. I am closing this issue now,
