### ISSUE TITLE
Link to file

### ISSUE THREAD

**Issue by pniederlag** [tritum/form_element_linked_checkbox#8]
Does anyone have a clue on how to link to a file (FAL) instead of a page?

**Comment by pniederlag** [comment]
it seems quite easily to make the element browser configurable for 'internal_type=db|file' to link to a file but yet it would have to be configured to use *either* db or file. I failed on a quick attempt to implement the TYPO3 Iink wizard in EXT:form in a similar manner to the TYPO3WinBrowserEditor.

**Comment by tritum** [comment]
This is possible now in TYPO3 v10. I know, we are not there yet, but dropping all of those constraints is a feaure :(

Please check the following patches:
* https://github.com/TYPO3/TYPO3.CMS/commit/3f9ab8220289ee8ff6fa1c879557853b87d151da
* https://github.com/TYPO3/TYPO3.CMS/commit/7675651dd4da039e074d9e75d1137fd8b5a4a812

Since we cannot resolve this with just changing this extension (but the core), I am closing this issue.

Thanks for taking care and using the extension :)
